#!/usr/bin/env node

/**
 * Script to replace environment variables in environment.prod.ts
 * Usage: node scripts/set-env.js
 * 
 * Required environment variables:
 * - API_URL: Backend API URL (e.g., https://api.yourdomain.com/api)
 * - SOCKET_URL: WebSocket URL (e.g., https://api.yourdomain.com)
 */

const fs = require('fs');
const path = require('path');

// Get environment variables
const apiUrl = process.env.API_URL || process.env.VITE_API_URL;
const socketUrl = process.env.SOCKET_URL || process.env.VITE_SOCKET_URL || apiUrl?.replace('/api', '');

if (!apiUrl) {
    console.warn('⚠️  Warning: API_URL environment variable not set. Using default values.');
    console.warn('   Set API_URL and SOCKET_URL environment variables for production deployment.');
    process.exit(0);
}

console.log('🔧 Setting production environment variables...');
console.log(`   API_URL: ${apiUrl}`);
console.log(`   SOCKET_URL: ${socketUrl}`);

// Path to environment.prod.ts
const envProdPath = path.join(__dirname, '../src/environments/environment.prod.ts');

// Create the new environment file content
const envContent = `// This file is auto-generated by scripts/set-env.js
// DO NOT EDIT MANUALLY - Changes will be overwritten during build

export const environment = {
  production: true,
  apiUrl: '${apiUrl}',
  socketUrl: '${socketUrl}'
};
`;

// Write the file
try {
    fs.writeFileSync(envProdPath, envContent, 'utf8');
    console.log('✅ Production environment configured successfully!');
} catch (error) {
    console.error('❌ Error writing environment file:', error);
    process.exit(1);
}
